### ISSUE TITLE
Не удаётся запустить Q.py

### ISSUE THREAD

**Issue by Mazdaywik** [ponyatov/Q#1]
При запуске выскакивает такое сообщение об ошибке:
```
D:\Mazdaywik\Documents\Q>python Q.py
Traceback (most recent call last):
  File "Q.py", line 730, in <module>
    restore()
  File "Q.py", line 293, in restore
    try: F = open(IMAGE,'rb') ; B = pickle.load(F) ; F.close()
  File "C:\Python27\lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 1069, in load_inst
    klass = self.find_class(module, name)
  File "C:\Python27\lib\pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named __main__
```

Если удалить файл `Q.py.image`, то программа после запуска зависает:

![q](https://user-images.githubusercontent.com/1309859/42761977-bcb3a398-8917-11e8-8be9-d8d6f3f309a1.PNG)

**Comment by ponyatov** [comment]
Под Windows ни разу не запускал, через пару дней посмотрю, возможно какие-то странности в кодировке концов строк.

**Comment by Mazdaywik** [comment]
Не удалось мне запустить под Linux, не собрался wxPython.
